# Generated by Django 3.2.15 on 2022-09-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresasparceiras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresasparceiras',
            old_name='image',
            new_name='imagem',
        ),
    ]
