# Generated by Django 3.2.15 on 2022-10-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_testemunhos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testemunhos',
            name='icone',
            field=models.CharField(choices=[('fa-comments', 'Messege')], max_length=12, verbose_name='Icone'),
        ),
    ]
