# Generated by Django 3.2.15 on 2022-11-25 14:30

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20221123_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicoadicionais',
            name='imagemAd',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 380, 'width': 380}}, verbose_name='Imagem'),
        ),
    ]
