# Generated by Django 3.2.15 on 2022-11-25 22:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_servicoadicionais_imagemad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicoadicionais',
            name='imagemAd',
            field=models.ImageField(height_field='380', max_length='500', upload_to=core.models.get_file_path, verbose_name='Imagem', width_field='380'),
        ),
    ]
