# Generated by Django 4.1 on 2022-08-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='imagem',
            field=models.ImageField(default=1, height_field='height', upload_to='service', width_field='width'),
            preserve_default=False,
        ),
    ]
