# Generated by Django 4.1 on 2022-08-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servico_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='serico',
            new_name='servico',
        ),
    ]
