# Generated by Django 3.2.15 on 2022-10-27 20:30

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_noticias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='image',
        ),
        migrations.AddField(
            model_name='noticias',
            name='imagem',
            field=stdimage.models.StdImageField(default='#', force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 300, 'width': 300}}, verbose_name='Imagem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticias',
            name='descricao',
            field=models.TextField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='link',
            field=models.CharField(max_length=300, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='manchete',
            field=models.CharField(max_length=100, verbose_name='Manchete'),
        ),
    ]
