# Generated by Django 3.2.15 on 2022-10-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_titulo_news_noticia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='noticia',
            new_name='titulo',
        ),
    ]
